<?php

namespace AppBundle\Repository;

/**
 * MooringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MooringRepository extends \Doctrine\ORM\EntityRepository
{
}
